export const UPLOAD_DATA = "UPLOAD_DATA";
export const GET_HOME_pAGE_DATA = "GET_HOME_pAGE_DATA";
export const GET_PRODUCT_WITH_CATEGORY = "GET_PRODUCT_WITH_CATEGORY";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_LIST = "GET_LIST";
export const REMOVE_FROM_LIST = "REMOVE_FROM_LIST";
export const ADD_TO_LIST = "ADD_TO_LIST";
